"use client";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Header from "./header/Header";
import Banner1 from "./banner/Banner1"
// import CreativeService from "./service/CreativeService"
import WhyChooseUs  from "./whyChooseUs/WhyChooseUs"
// import Testimonial1 from "./testimonial/Testimonial1"
import Footer2 from "./footer/Footer2";
import Preloader from "./common/Preloader "



export default function Home() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 1500);
  }, []);

  return (
    <>
      {/* {!loading ? (
        <Preloader />
      ) : (
        <>
          <Head>
            <title>WorkDeal</title>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            ></meta>
            <meta name="description" content="Generated by create next app" />
            <link
              rel="icon"
              href="assets/images/fevicon.png"
              type="image/gif"
              sizes="20x20"
            />
          </Head> */}
          <Header/>
          <Banner1 />
          {/* <CreativeService /> */}
          {/* <WhyChooseUs /> */}
          {/* <Testimonial1 /> */}
         
          <Footer2 />
        </>
      )}
//     </>
//   );
// }
