
import "./globals.css";
import Head from "next/head";
import React from "react";

import Footer2 from "./footer/Footer2";
import Header2 from "./header/Header2";
import { MyProvider } from "./context";

function Layout({ children }
  :{
    children:React.ReactNode;
  }) {
  return (
    
<html>
<Head>
        <title>Workdeal</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/favicon.png"
          type="image/gif"
          sizes="20x20"
        />
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"  /> */}
      </Head>
      <body style={{backgroundColor:"white"}}>
      {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
     integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
    ></script> */}
      
      <MyProvider> {children}</MyProvider> </body>
</html>
    
  );
}

export default Layout;

